-
  name: Copy files to target servers
  hosts: all
#  vars:
#     webserver_file: '/tmp/test-file.txt'
  tasks:
    - name: Copy files to target servers
      copy:
         src: /tmp/test-file.txt
         dest: /tmp/test-file.txt

    - name: Check line to the file and add if it does not exist
      lineinfile:
         path: '{{ webserver_file }}'
         line: 'nameserver x.x.x.x'
